"""
PDF Report Generator — Generates downloadable PDF reports for interview sessions.
Uses a simple HTML-to-text approach without heavy dependencies.
"""

from datetime import datetime


def generate_report_text(session, evaluation, questions):
    """
    Generates a plain-text interview report.
    For full PDF generation, integrate with reportlab or weasyprint.
    """
    lines = []
    lines.append("=" * 60)
    lines.append("          INTELLIHIRE — INTERVIEW EVALUATION REPORT")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"  Candidate:    User #{session.user_id}")
    lines.append(f"  Company:      {session.company_name}")
    lines.append(f"  Role:         {session.job_role}")
    lines.append(f"  Domain:       {session.domain}")
    lines.append(f"  Difficulty:   {session.difficulty}")
    lines.append(f"  Answer Mode:  {session.answer_mode}")
    lines.append(f"  Date:         {session.started_at.strftime('%B %d, %Y') if session.started_at else 'N/A'}")
    lines.append("")
    lines.append("-" * 60)
    lines.append("  FINAL SCORE")
    lines.append("-" * 60)
    lines.append("")

    if evaluation:
        lines.append(f"  Overall Score:  {evaluation.final_score:.1f}%")
        lines.append(f"  Recommendation: {evaluation.recommendation or 'N/A'}")
        lines.append("")
        lines.append(f"  HR / Communication:   {evaluation.hr_overall:.1f} / 10")
        lines.append(f"  Technical:            {evaluation.technical_overall:.1f} / 10")
        lines.append(f"  Stress / Composure:   {evaluation.stress_overall:.1f} / 10")
        lines.append(f"  Company Fit:          {evaluation.company_fit:.1f} / 10")
        lines.append("")

        if evaluation.coordinator_feedback:
            lines.append("-" * 60)
            lines.append("  COORDINATOR FEEDBACK")
            lines.append("-" * 60)
            lines.append(f"  {evaluation.coordinator_feedback}")
            lines.append("")

        if evaluation.strengths:
            lines.append("-" * 60)
            lines.append("  TOP STRENGTHS")
            lines.append("-" * 60)
            for s in evaluation.strengths:
                lines.append(f"  ✓ {s}")
            lines.append("")

        if evaluation.improvements:
            lines.append("-" * 60)
            lines.append("  AREAS FOR IMPROVEMENT")
            lines.append("-" * 60)
            for s in evaluation.improvements:
                lines.append(f"  ⚠ {s}")
            lines.append("")

        if evaluation.roadmap:
            steps = evaluation.roadmap.get("steps", []) if isinstance(evaluation.roadmap, dict) else evaluation.roadmap
            if steps:
                lines.append("-" * 60)
                lines.append("  LEARNING ROADMAP")
                lines.append("-" * 60)
                for i, step in enumerate(steps, 1):
                    lines.append(f"  {i}. {step}")
                lines.append("")
    else:
        lines.append("  No evaluation data available.")
        lines.append("")

    # Question & Answer Details
    lines.append("-" * 60)
    lines.append("  QUESTION & ANSWER DETAILS")
    lines.append("-" * 60)
    lines.append("")

    for q in questions:
        lines.append(f"  Q{q.order_number}: [{q.question_type}] {q.question_text}")
        answer = q.text_answer or q.transcript or "(No answer)"
        lines.append(f"  A: {answer[:500]}")
        if q.question_feedback:
            lines.append(f"  Feedback: {q.question_feedback}")
        lines.append("")

    lines.append("=" * 60)
    lines.append(f"  Generated by IntelliHire on {datetime.utcnow().strftime('%B %d, %Y at %H:%M UTC')}")
    lines.append("=" * 60)

    return "\n".join(lines)
